version: '3'

volumes:
  neo-applogs:
  neo-chain:

services:

  # NEO CLI node
  neo-node:
    build: .
    image: neo-node
    expose:
      - 10332 # expose port for other services
    ports:
      - 10332:10332 # expose port to host system for debugging and health check purposes
    tty: true # needed for screen (neo-cli doesn't work otherwise)
    volumes:
      - neo-applogs:/applogs
      - neo-chain:/chain

  # grabber service
  neo-xplr:
    depends_on:
      - neo-node
    build: ./neo-blockchain-explorer
    image: neo-xplr
    environment:
      NEO_EXPLORER_NEO_NODE: http://neo-node:10332
      NEO_EXPLORER_DB_NAME: duxi_neo
      NEO_EXPLORER_RETHINK: ${NEO_EXPLORER_RETHINK}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
